import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from "../components/SideBar"
import ClientProvider from "../components/ClientProvider"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html>
      <head />
      <body>
          
        <div className="flex">
          {/* Sidebar */}
          <div className="bg-[#202123] max-w-xs h-screen overflow-y-scroll
          md:min-w-[20rem]">
            <Sidebar />
          </div>
          {/* client provider*/}
          <ClientProvider />
          
        <div className="bg-[#343541] flex-1" >
          {children}
          </div>
        </div>
    
        </body>
    </html>
  )
}